apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtvrc4533-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtvrc4533-tenant-component
    app.kubernetes.io/part-of: loadtvrc4533-tenant-app
  name: loadtvrc4533-tenant-component
  namespace: loadtvrc4533-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: loadtvrc4533-tenant-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: loadtvrc4533-tenant-component
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/test-images:bd2eaaad55fc47b7832f1dccde2fd582
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
